### ISSUE TITLE
NaniteLifeSupportTargets.DoesTargetNeedLifeSupport produces NullReferenceException

### ISSUE THREAD

**Issue by Clashsoft** [Nanite-Construction-System/NaniteConstructionSystem#141]
```
ProcessTargetsParallel() Error. Clearing blockcache.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.MyVisualScriptLogicProvider.GetPlayersHealth(Int64 playerId)
   at NaniteConstructionSystem.Entities.Targets.NaniteLifeSupportTargets.DoesTargetNeedLifeSupport(IMyPlayer player)
   at NaniteConstructionSystem.Entities.Targets.NaniteLifeSupportTargets.ParallelUpdate(List`1 gridList, List`1 gridBlocks)
   at NaniteConstructionSystem.Entities.NaniteConstructionBlock.ProcessTargetsParallel()
```

**Comment by M0dEx** [comment]
Hi @Clashsoft,

I'll need you to do the following:

1. Go to %AppData%\SpaceEngineers\Saves\\<steam_id>\\<world_name>\Storage\219757726.sbm_NaniteConstructionSystem, open Config.xml and change `<DebugLogging>0</DebugLogging>` to `<DebugLogging>2</DebugLogging>`
2. Load the save in the game and replicate the issue.
3. Post NaniteConstructionSystem.log, SpaceEngineers\_\<date\>.log and the save as a reply to this issue.

Thanks!

**Comment by M0dEx** [comment]
Fixed
