### ISSUE TITLE
Crashing SE server

### ISSUE THREAD

**Issue by netthier** [Nanite-Construction-System/NaniteConstructionSystem#167]
After installing the mod, my SE server crashed after a few hours of activity.
The server logs didn't contain any errors, but NaniteConstructionSystem.log logged the following at the exact moment of the crash:
`[16:17:12] ProcessTargets InvalidOperationException: A list was modified during enumeration in a parallel thread, which is likely harmless.`

**Comment by DarthWar** [comment]
Crashing Torch Server but not local single player.

**Comment by jo-nat** [comment]
Hey we're getting this random error on starting our Torch instance with your mod. Torch throws a fit shortly after this and closes.

```
17:01:50.5764 [DEBUG]  Keen: ERROR Entity init!: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NaniteConstructionSystem.Entities.NaniteAssemblerLogic.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCompositeGameLogicComponent.Init(MyObjectBuilder_EntityBase objectBuilder)
   at VRage.Game.Entity.MyEntity.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCubeBlock.Init(MyObjectBuilder_CubeBlock builder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyProductionBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyAssembler.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MySlimBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid, MyCubeBlock fatBlock)
   at Sandbox.Game.Entities.MyCubeGrid.AddCubeBlock_Patch1(MyCubeGrid this, MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge, MyCubeBlockDefinition blockDefinition)
   at Sandbox.Game.Entities.MyCubeGrid.AddBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge)
   at Sandbox.Game.Entities.MyCubeGrid.InitInternal(MyObjectBuilder_EntityBase objectBuilder, Boolean rebuildGrid)
   at Sandbox.Game.Entities.MyCubeGrid.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyEntities.InitEntity(MyObjectBuilder_EntityBase objectBuilder, MyEntity& entity, Boolean tolerateBlacklistedPlanets)
17:01:50.5764 [DEBUG]  Keen:    ERROR Entity init!: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at NaniteConstructionSystem.Entities.NaniteAssemblerLogic.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCompositeGameLogicComponent.Init(MyObjectBuilder_EntityBase objectBuilder)
   at VRage.Game.Entity.MyEntity.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyCubeBlock.Init(MyObjectBuilder_CubeBlock builder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyTerminalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyFunctionalBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyProductionBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MyAssembler.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid)
   at Sandbox.Game.Entities.Cube.MySlimBlock.Init(MyObjectBuilder_CubeBlock objectBuilder, MyCubeGrid cubeGrid, MyCubeBlock fatBlock)
   at Sandbox.Game.Entities.MyCubeGrid.AddCubeBlock_Patch1(MyCubeGrid this, MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge, MyCubeBlockDefinition blockDefinition)
   at Sandbox.Game.Entities.MyCubeGrid.AddBlock(MyObjectBuilder_CubeBlock objectBuilder, Boolean testMerge)
   at Sandbox.Game.Entities.MyCubeGrid.InitInternal(MyObjectBuilder_EntityBase objectBuilder, Boolean rebuildGrid)
   at Sandbox.Game.Entities.MyCubeGrid.Init(MyObjectBuilder_EntityBase objectBuilder)
   at Sandbox.Game.Entities.MyEntities.InitEntity(MyObjectBuilder_EntityBase objectBuilder, MyEntity& entity, Boolean tolerateBlacklistedPlanets)
```

**Comment by jo-nat** [comment]
Following that we get this error and Torch closes:

```
17:01:55.2969 [ERROR]  Keen:    Error during loading session:Sandbox.Game.Screens.MyLoadingException: An error occurred while loading the world.
The world may be corrupted and can't be loaded.
Please, restart the game and try again.
   at Sandbox.Game.World.MySession.ShowLoadingError(Boolean lobbyFailed, MyLobbyStatusCode statusCode, Nullable`1 errorMessage)
   at Sandbox.Game.World.MySession.LoadWorld(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
17:01:55.2969 [INFO]   Keen:    Exception while loading world: An error occurred while loading the world.
The world may be corrupted and can't be loaded.
Please, restart the game and try again.
17:01:55.2969 [DEBUG]  Keen:       at Sandbox.Game.World.MySession.ShowLoadingError(Boolean lobbyFailed, MyLobbyStatusCode statusCode, Nullable`1 errorMessage)
   at Sandbox.Game.World.MySession.LoadWorld(MyObjectBuilder_Checkpoint checkpoint, MyObjectBuilder_Sector sector)
   at Sandbox.Game.World.MySession.Load(String sessionPath, MyObjectBuilder_Checkpoint checkpoint, UInt64 checkpointSizeInBytes, Boolean saveLastStates, Boolean allowXml)
   at Patched_Sandbox.MySandboxGameInitQuickLaunch_0(Object )```
