### ISSUE TITLE
Nanite Mod will not load. Tested as the only mod and this is the errors i get.

### ISSUE THREAD

**Issue by BetaVirus** [Nanite-Construction-System/NaniteConstructionSystem#178]
I checked for the mod in the mods folder but it is blank. also tested in empty world.
-- EDIT: I had two folder for the steam. looks like it was in the second Drive Z. Cleared the mod and it redownload in solo game with no errors.
-- Testing in game with more mods and issue resolve as well. But now i have to fix different mods... seems downloads are buggy when loading a game.
====================================================
MOD_CRITICAL_ERROR: Nanite Control Facility v2.0(15) - Automated Construction, in file: Unknown
MOD PARTIALLY SKIPPED, LOADED ONLY 1/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: Nanite Control Facility v2.0(15) - Automated Construction, in file: Unknown
MOD PARTIALLY SKIPPED, LOADED ONLY 2/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: Nanite Control Facility v2.0(15) - Automated Construction, in file: Unknown
MOD PARTIALLY SKIPPED, LOADED ONLY 3/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: Nanite Control Facility v2.0(15) - Automated Construction, in file: Unknown
MOD PARTIALLY SKIPPED, LOADED ONLY 4/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: Nanite Control Facility v2.0(15) - Automated Construction, in file: Unknown
MOD PARTIALLY SKIPPED, LOADED ONLY 5/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: Nanite Control Facility v2.0(15) - Automated Construction, in file: Unknown
MOD PARTIALLY SKIPPED, LOADED ONLY 6/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)

**Comment by BetaVirus** [comment]
Issue resolved with delete and redownload
