### ISSUE TITLE
something to do with Particle effects and cleanup

### ISSUE THREAD

**Issue by nukeguard** [Nanite-Construction-System/NaniteConstructionSystem#83]
2018-12-24 05:17:33.523 - Thread:  17 ->  NaniteConstructionSystem.Particles.ParticleEffectManager.Cleanup:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at NaniteConstructionSystem.Particles.ParticleEffectManager.<>c__DisplayClass6_0.<Cleanup>b__0(TargetEntity item)
2018-12-24 05:17:33.551 - Thread:   1 ->  Exception occured: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at NaniteConstructionSystem.Particles.ParticleEffectManager.<>c__DisplayClass6_0.<Cleanup>b__1()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)

**Comment by SplenectomY** [comment]
Will fix before V2.

**Comment by SplenectomY** [comment]
@nukeguard was this a fatal crash or just some message that popped up in the console?

**Comment by nukeguard** [comment]
I just got this crash today, and it was a fatal crash, I was using the version you have online. 

 2019-01-02 09:12:04.048 - Thread:  14 ->  NaniteConstructionSystem.Particles.ParticleEffectManager.Cleanup:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at NaniteConstructionSystem.Particles.ParticleEffectManager.<>c__DisplayClass6_0.<Cleanup>b__0(TargetEntity item)
2019-01-02 09:12:04.108 - Thread:   1 ->  Exception occured: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at NaniteConstructionSystem.Particles.ParticleEffectManager.<>c__DisplayClass6_0.<Cleanup>b__1()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.Main(String[] args)
2019-01-02 09:12:04.110 - Thread:   1 ->  Hiding window

**Comment by SplenectomY** [comment]
That's very strange, considering that the error here is printed from a catch block. Let me take a deeper look at it.

**Comment by SplenectomY** [comment]
@nukeguard I just pushed an update. Download the latest version and see if it still happens.
